./train.sh ArtNouveau
./train.sh Dadaism
./train.sh fauvism
./train.sh gothic2
./train.sh impressionism
./train.sh mosaic2
./train.sh piccaso
./train.sh popart2
./train.sh realism
./train.sh train.sh
./train.sh thotavaikuntam
./train.sh Cubism
./train.sh Expressionism
./train.sh Futurism
./train.sh gothic
./train.sh mononoke
./train.sh mosaic
./train.sh piexl
./train.sh popart
./train.sh Suprematism
./train.sh tokyo
